spring.application.name=security
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
logging.level.org.springframework.security=DEBUG
jwt.secret=d3b07384d113edec49eaa6238ad5ff00f5d1a6454c8e3fbef0d7c3bfcf4b9d7f
hibernate.search.index.directory=./hibernate-search-indexes
hibernate.search.backend.analysis.configurer=com.hackertracker.security.config.MyLuceneAnalysisConfigurer
spring.datasource.url=jdbc:mysql://localhost:3306/hack_bis?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
hibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.show_sql=true
hibernate.format_sql=true