spring.application.name=security
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
logging.level.org.springframework.security=DEBUG
jwt.secret=d3b07384d113edec49eaa6238ad5ff00f5d1a6454c8e3fbef0d7c3bfcf4b9d7f